# This is a basic workflow to help you get started with Actions

name: Update Plots

# Controls when the action will run. 
on:
  schedule:
  - cron: "0 18 * * *"
    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    
      - name: Run plot.py
        run: python plot.py
        
      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        if: ${{ git status -s --untracked-files=no }}
        with:
          author_name: Github Action
          author_email: carlin.mackenzie@gmail.com
          message: "Update plots"
          add: "-u"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
